#!/usr/bin/env python3
"""
gen_build_info.py — derleme öncesi adım (tasarım §9, MSG-09, V6).

Core/Inc/build_info.h dosyasını üretir:
    #define BUILD_GIT_HASH "a1b2c3d"     (temiz)
    #define BUILD_GIT_HASH "a1b2c3d+"    (hafta-01/firmware altında commit edilmemiş değişiklik var)
    #define BUILD_GIT_HASH "nogit"       (git bulunamadı)

STM32CubeIDE → Project Properties → C/C++ Build → Settings → Build Steps → Pre-build steps
(Debug ve Release için ayrı ayrı):
    py "${ProjDirPath}/../tools/gen_build_info.py" "${ProjDirPath}/Core/Inc/build_info.h"

Dosya yalnızca içerik değiştiğinde yeniden yazılır (gereksiz yeniden derlemeyi önler).
build_info.h .gitignore'dadır.
"""
import pathlib
import subprocess
import sys


def git(*args, cwd):
    return subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True, check=True).stdout.strip()


def main(out_path):
    out = pathlib.Path(out_path).resolve()
    fw_dir = pathlib.Path(__file__).resolve().parents[1]          # hafta-01/firmware
    try:
        h = git("rev-parse", "--short=7", "HEAD", cwd=fw_dir)
        dirty = git("status", "--porcelain", "--untracked-files=no", "--", ".", cwd=fw_dir)
        if dirty:
            h += "+"
    except (OSError, subprocess.CalledProcessError):
        h = "nogit"
    text = ("/* Generated by firmware/tools/gen_build_info.py - do not edit. */\n"
            "#ifndef BUILD_INFO_H\n#define BUILD_INFO_H\n"
            f'#define BUILD_GIT_HASH "{h}"\n'
            "#endif\n")
    if not out.exists() or out.read_text(encoding="ascii") != text:
        out.write_text(text, encoding="ascii")
    print(f"build_info.h: BUILD_GIT_HASH = {h}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "build_info.h")
